name: Workflow

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'Gemfile.lock'

permissions:
  contents: write
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor == 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Echo git status
      run: |
          output=$(git status)
          echo $output

    - name: Echo git log
      run: |
          output=$(git log -1 HEAD)
          echo $output

    - name: Try to checkout
      run: |
          git checkout ${{ github.head_ref }}

  job2:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Echo
      run: |
          echo "Actor"
