name: Workflow

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "Gemfile.lock"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

# Only allow one run of this per branch. Cancel any existing ones when re-triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Echo git status
        run: |
          output=$(git status)
          echo $output

      - name: Echo git log
        run: |
          output=$(git log -1 HEAD)
          echo $output

      - name: Try to checkout
        run: |
          git checkout ${{ github.head_ref }}

      - name: Failure
        id: setup
        run: |
          exit 1

      - name: Failure message
        if: ${{ failure() && steps.setup.conclusion == 'failure' }}
        run: |
          echo "Failed during setup"
