name: Reusable

on:
  workflow_call:
    inputs:
      runner:
        description: Specify the runner
        type: string
        default: 'self-hosted'
        required: false

jobs:
  reusable:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Hello world
        run: echo "Hello world"
